# Generated by Django 5.2.11 on 2026-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usuario',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('permisos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_usuario',
            },
        ),
    ]
