# Generated by Django 5.2.11 on 2026-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_usuario',
            name='codigo_diseno',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
