# Generated by Django 5.2.11 on 2026-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_tbl_usuario_emblema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_usuario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tbl_usuario',
            name='emblema',
        ),
        migrations.RemoveField(
            model_name='tbl_usuario',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='tbl_usuario',
            name='permisos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
