# Generated by Django 5.2.11 on 2026-03-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_tbl_usuario_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_usuario',
            table='tbl_usuario',
        ),
    ]
