# Generated by Django 5.2.11 on 2026-03-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pregunta_ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_respuesta', models.BooleanField(default=False)),
                ('fecha_respondida', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_asociadas', to='pregunta.tbl_preguntas')),
            ],
            options={
                'db_table': 'tbl_pregunta_ronda',
            },
        ),
    ]
