# Generated by Django 5.2.11 on 2026-03-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pregunta_ronda', '0001_initial'),
        ('ronda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pregunta_ronda',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_asociadas', to='ronda.tbl_rondas'),
        ),
        migrations.AlterUniqueTogether(
            name='tbl_pregunta_ronda',
            unique_together={('pregunta', 'ronda')},
        ),
    ]
