# Generated by Django 5.2.11 on 2026-03-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pregunta', '0001_initial'),
        ('pregunta_ronda', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rondas',
            fields=[
                ('id_ronda', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.FloatField(default=0.0)),
                ('fecha_jugado', models.DateTimeField(auto_now_add=True)),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='usuario.tbl_usuario')),
                ('preguntas', models.ManyToManyField(through='pregunta_ronda.tbl_pregunta_ronda', to='pregunta.tbl_preguntas')),
            ],
            options={
                'db_table': 'tbl_rondas',
            },
        ),
    ]
