# Generated by Django 5.2.11 on 2026-03-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_rondas',
            table='tbl_rondas',
        ),
    ]
