# Generated by Django 5.2.11 on 2026-03-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.BooleanField(default=False)),
                ('explicacion', models.TextField(blank=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='categoria.tbl_categoria')),
            ],
            options={
                'db_table': 'tbl_preguntas',
            },
        ),
    ]
