# Generated by Django 5.2.11 on 2026-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pregunta_ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_respuesta', models.BooleanField(default=False)),
                ('fecha_respondida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '[api_genio].[tbl_pregunta_ronda]',
            },
        ),
        migrations.CreateModel(
            name='tbl_preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.BooleanField(default=False)),
                ('explicacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': '[api_genio].[tbl_preguntas]',
            },
        ),
    ]
