# Generated by Django 5.2.11 on 2026-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_preguntas',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
