# Generated by Django 5.2.11 on 2026-02-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('pregunta', '0001_initial'),
        ('ronda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pregunta_ronda',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_asociadas', to='ronda.tbl_rondas'),
        ),
        migrations.AddField(
            model_name='tbl_preguntas',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='categoria.tbl_categoria'),
        ),
        migrations.AddField(
            model_name='tbl_pregunta_ronda',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_asociadas', to='pregunta.tbl_preguntas'),
        ),
        migrations.AlterUniqueTogether(
            name='tbl_pregunta_ronda',
            unique_together={('pregunta', 'ronda')},
        ),
    ]
