# Generated by Django 5.2.11 on 2026-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje', models.FloatField(default=0.0)),
                ('tiempo_limite', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
    ]
