# Generated by Django 5.2.11 on 2026-03-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_categoria',
            table='tbl_categoria',
        ),
    ]
