# Generated by Django 5.2.11 on 2026-03-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_disenos',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('color_primario', models.CharField(blank=True, default='', max_length=20)),
                ('fuente', models.CharField(blank=True, default='', max_length=100)),
                ('fondo_nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('fondo_url', models.TextField(blank=True, default='')),
                ('logo_nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('fecha_expiracion', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_disenos',
            },
        ),
        migrations.CreateModel(
            name='tbl_preguntas_diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_id', models.IntegerField()),
                ('pregunta', models.TextField()),
                ('respuesta', models.BooleanField()),
                ('explicacion', models.TextField()),
                ('categoria', models.IntegerField(default=1)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='diseno.tbl_disenos')),
            ],
            options={
                'db_table': 'tbl_preguntas_diseno',
                'unique_together': {('diseno', 'pregunta_id')},
            },
        ),
    ]
