# Generated by Django 5.2.11 on 2026-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_disenos',
            name='app_subtitulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='app_tagline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='app_titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='icono_f_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='icono_fallaste_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='icono_v_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_disenos',
            name='icono_victoria_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
